/* global React */
// Trend PM — seed data (شركة ترند التقنية)

const TEAM = [
  { id: "u1", name: "سارة الراشد", en: "Sarah Al-Rashed", role: "Product Manager", initials: "SR", hue: 180 },
  { id: "u2", name: "عمر الزهراني", en: "Omar Al-Zahrani", role: "Tech Lead", initials: "OZ", hue: 30 },
  { id: "u3", name: "ليلى الحربي", en: "Layla Al-Harbi", role: "Senior Backend", initials: "LH", hue: 320 },
  { id: "u4", name: "يوسف العتيبي", en: "Youssef Al-Otaibi", role: "Frontend Dev", initials: "YO", hue: 260 },
  { id: "u5", name: "مريم الشمري", en: "Maryam Al-Shammari", role: "UI/UX Designer", initials: "MS", hue: 140 },
  { id: "u6", name: "خالد القحطاني", en: "Khaled Al-Qahtani", role: "DevOps", initials: "KQ", hue: 210 },
  { id: "u7", name: "نورة السبيعي", en: "Noura Al-Subaie", role: "QA Engineer", initials: "NS", hue: 350 },
  { id: "u8", name: "فيصل الدوسري", en: "Faisal Al-Dosari", role: "Backend Dev", initials: "FD", hue: 80 },
  { id: "u9", name: "ريم المطيري", en: "Reem Al-Mutairi", role: "Data Engineer", initials: "RM", hue: 110 },
];

const PROJECTS = [
  {
    id: "p1", key: "PAY", name: "بوابة الدفع الإلكتروني", en: "Payment Gateway v2",
    client: "بنك الإتحاد", pm: "u1", color: "#8B5CF6",
    status: "Active", priority: "Critical",
    start: "2026-02-15", due: "2026-05-30",
    budget: 420000, spent: 268000,
    tags: ["Fintech", "Backend"],
    progress: 62,
  },
  {
    id: "p2", key: "CRM", name: "نظام إدارة العملاء الموحّد", en: "Unified CRM",
    client: "ترند — داخلي", pm: "u2", color: "#38BDF8",
    status: "Active", priority: "High",
    start: "2026-01-08", due: "2026-06-20",
    budget: 310000, spent: 149000,
    tags: ["Internal", "Fullstack"],
    progress: 48,
  },
  {
    id: "p3", key: "DSH", name: "لوحة التحليلات اللحظية", en: "Realtime Analytics Dashboard",
    client: "مجموعة الأفق", pm: "u1", color: "#F59E0B",
    status: "Active", priority: "High",
    start: "2026-03-01", due: "2026-07-10",
    budget: 280000, spent: 92000,
    tags: ["Data", "Frontend"],
    progress: 33,
  },
  {
    id: "p4", key: "MOB", name: "تطبيق iOS — الإصدار الثالث", en: "iOS App v3",
    client: "ترند — عام", pm: "u5", color: "#10B981",
    status: "Active", priority: "Medium",
    start: "2026-02-01", due: "2026-05-15",
    budget: 180000, spent: 124000,
    tags: ["Mobile", "iOS"],
    progress: 71,
  },
  {
    id: "p5", key: "INF", name: "ترقية البنية السحابية", en: "Cloud Infra Upgrade",
    client: "ترند — داخلي", pm: "u6", color: "#F43F5E",
    status: "On Hold", priority: "Medium",
    start: "2026-01-20", due: "2026-04-30",
    budget: 140000, spent: 86000,
    tags: ["DevOps", "Infra"],
    progress: 40,
  },
  {
    id: "p6", key: "DOC", name: "بوابة التوثيق للمطورين", en: "Developer Docs Portal",
    client: "ترند — عام", pm: "u4", color: "#06B6D4",
    status: "Planning", priority: "Low",
    start: "2026-04-10", due: "2026-06-30",
    budget: 60000, spent: 0,
    tags: ["Docs"],
    progress: 8,
  },
];

// Status: todo | progress | review | blocked | done
// Priority: low | med | high | crit
function T(id, proj, title, opts = {}) {
  return {
    id,
    projectId: proj,
    title,
    status: opts.s || "todo",
    priority: opts.p || "med",
    assignees: opts.a || [],
    due: opts.due,
    start: opts.start,
    est: opts.est || 0,
    spent: opts.spent || 0,
    progress: opts.prog ?? 0,
    tags: opts.tags || [],
    comments: opts.comments || 0,
    attachments: opts.att || 0,
    deps: opts.deps || [],
    parent: opts.parent || null,
    description: opts.desc || "",
    subtasks: opts.subtasks || [],
    createdAt: opts.createdAt || "2026-03-01",
  };
}

const TASKS = [
  // PAY
  T("PAY-12", "p1", "إعادة هيكلة خدمة تفويض البطاقات", { s: "progress", p: "crit", a: ["u2", "u8"], start: "2026-04-06", due: "2026-04-22", est: 40, spent: 26, prog: 65, tags: ["backend", "security"], comments: 8, att: 2, deps: [] }),
  T("PAY-13", "p1", "تكامل بوابة مدى — اختبار التشفير", { s: "review", p: "crit", a: ["u2"], start: "2026-04-10", due: "2026-04-19", est: 16, spent: 18, prog: 100, tags: ["backend"], comments: 12, att: 5 }),
  T("PAY-14", "p1", "تصميم شاشة الدفع — حالات الخطأ", { s: "progress", p: "high", a: ["u5"], start: "2026-04-08", due: "2026-04-24", est: 20, spent: 11, prog: 55, tags: ["design"], comments: 3 }),
  T("PAY-15", "p1", "إعداد بيئة الاختبار للعميل", { s: "blocked", p: "high", a: ["u6"], start: "2026-04-12", due: "2026-04-17", est: 8, spent: 6, prog: 40, tags: ["devops"], comments: 5, deps: ["PAY-12"] }),
  T("PAY-16", "p1", "توثيق API للتكامل الخارجي", { s: "todo", p: "med", a: ["u8"], start: "2026-04-22", due: "2026-05-02", est: 12, prog: 0, tags: ["docs"] }),
  T("PAY-17", "p1", "اختبار الحمل — 10k req/s", { s: "todo", p: "high", a: ["u7", "u6"], start: "2026-05-01", due: "2026-05-10", est: 24, prog: 0, tags: ["qa"] }),
  T("PAY-18", "p1", "معالجة حالة الاسترداد الجزئي", { s: "todo", p: "med", a: ["u2"], start: "2026-05-05", due: "2026-05-15", est: 16, prog: 0, tags: ["backend"] }),
  T("PAY-19", "p1", "مراجعة أمنية خارجية", { s: "todo", p: "crit", a: [], start: "2026-05-20", due: "2026-05-28", est: 32, prog: 0, tags: ["security"] }),
  T("PAY-10", "p1", "ترحيل قاعدة البيانات إلى Postgres 17", { s: "done", p: "high", a: ["u9"], start: "2026-03-02", due: "2026-03-18", est: 24, spent: 22, prog: 100 }),
  T("PAY-11", "p1", "إعداد مخطط العلاقات للمعاملات", { s: "done", p: "high", a: ["u8"], start: "2026-03-15", due: "2026-03-28", est: 16, spent: 14, prog: 100 }),
  T("PAY-20", "p1", "إصلاح تسريب ذاكرة في العامل الخلفي", { s: "progress", p: "high", a: ["u2"], start: "2026-04-14", due: "2026-04-16", est: 6, spent: 5, prog: 75, tags: ["bug"], comments: 4 }),

  // CRM
  T("CRM-22", "p2", "نموذج إضافة جهة اتصال — تحقق Zod", { s: "progress", p: "med", a: ["u4"], start: "2026-04-08", due: "2026-04-20", est: 14, spent: 8, prog: 55, tags: ["frontend"], comments: 2 }),
  T("CRM-23", "p2", "Import من Excel — مطابقة الحقول", { s: "review", p: "high", a: ["u4", "u8"], start: "2026-04-05", due: "2026-04-18", est: 20, spent: 22, prog: 100, tags: ["frontend", "backend"], comments: 6, att: 3 }),
  T("CRM-24", "p2", "فلاتر متقدّمة + حفظ الاستعلامات", { s: "todo", p: "med", a: ["u4"], start: "2026-04-22", due: "2026-05-05", est: 18, prog: 0 }),
  T("CRM-25", "p2", "تكامل مع الواتساب الرسمي", { s: "blocked", p: "high", a: ["u2"], start: "2026-04-12", due: "2026-04-15", est: 12, spent: 4, prog: 30, deps: ["CRM-23"], comments: 7 }),
  T("CRM-26", "p2", "تصميم صفحة العميل — الجدول الزمني", { s: "progress", p: "med", a: ["u5"], start: "2026-04-10", due: "2026-04-24", est: 16, spent: 9, prog: 50 }),
  T("CRM-27", "p2", "تقارير المبيعات الشهرية", { s: "todo", p: "low", a: ["u9"], start: "2026-05-01", due: "2026-05-20", est: 24, prog: 0 }),
  T("CRM-20", "p2", "إعداد نموذج البيانات الأوّلي", { s: "done", p: "high", a: ["u2"], start: "2026-01-20", due: "2026-02-10", est: 30, spent: 28, prog: 100 }),
  T("CRM-21", "p2", "Auth + Workspaces", { s: "done", p: "crit", a: ["u2", "u8"], start: "2026-02-05", due: "2026-02-28", est: 40, spent: 45, prog: 100 }),

  // DSH
  T("DSH-8", "p3", "مخطط البيانات اللحظية — Kafka", { s: "progress", p: "high", a: ["u9", "u6"], start: "2026-04-02", due: "2026-04-25", est: 32, spent: 18, prog: 45 }),
  T("DSH-9", "p3", "Widget محرر السحب والإفلات", { s: "progress", p: "high", a: ["u4"], start: "2026-04-05", due: "2026-04-28", est: 28, spent: 14, prog: 40, comments: 3 }),
  T("DSH-10", "p3", "مخطط التدفق الجغرافي", { s: "review", p: "med", a: ["u5", "u4"], start: "2026-04-01", due: "2026-04-16", est: 14, spent: 16, prog: 100, comments: 4 }),
  T("DSH-11", "p3", "تصدير PDF/Excel", { s: "todo", p: "med", a: ["u4"], start: "2026-04-28", due: "2026-05-10", est: 12, prog: 0 }),
  T("DSH-12", "p3", "نظام التنبيهات — القواعد", { s: "todo", p: "high", a: ["u8"], start: "2026-05-01", due: "2026-05-25", est: 36, prog: 0 }),
  T("DSH-13", "p3", "اختبار الأداء على 1M نقطة", { s: "todo", p: "high", a: ["u7"], start: "2026-05-20", due: "2026-06-05", est: 24, prog: 0 }),
  T("DSH-7", "p3", "دراسة المتطلبات + Wireframes", { s: "done", p: "high", a: ["u1", "u5"], start: "2026-03-01", due: "2026-03-20", est: 40, spent: 36, prog: 100 }),

  // MOB
  T("MOB-18", "p4", "شاشة التسجيل — OAuth Apple", { s: "review", p: "high", a: ["u5"], start: "2026-04-06", due: "2026-04-18", est: 16, spent: 15, prog: 100, comments: 5 }),
  T("MOB-19", "p4", "إشعارات Push — APNs", { s: "progress", p: "med", a: ["u6"], start: "2026-04-10", due: "2026-04-22", est: 12, spent: 7, prog: 60 }),
  T("MOB-20", "p4", "وضع داكن — مراجعة التباين", { s: "progress", p: "low", a: ["u5"], start: "2026-04-08", due: "2026-04-20", est: 10, spent: 5, prog: 50 }),
  T("MOB-21", "p4", "إصلاح تعطّل عند الشبكة البطيئة", { s: "blocked", p: "crit", a: [], start: "2026-04-12", due: "2026-04-14", est: 8, spent: 3, prog: 25, tags: ["bug"], comments: 9 }),
  T("MOB-22", "p4", "إعداد Release للمتجر", { s: "todo", p: "high", a: ["u6"], start: "2026-05-01", due: "2026-05-12", est: 10, prog: 0 }),

  // INF
  T("INF-5", "p5", "ترحيل إلى Kubernetes 1.30", { s: "blocked", p: "high", a: ["u6"], start: "2026-03-20", due: "2026-04-10", est: 50, spent: 38, prog: 70, comments: 6 }),
  T("INF-6", "p5", "إعادة هيكلة الـ CI/CD", { s: "progress", p: "med", a: ["u6"], start: "2026-04-01", due: "2026-04-25", est: 30, spent: 16, prog: 55 }),
  T("INF-7", "p5", "مراجعة تكلفة السحابة", { s: "todo", p: "low", a: ["u6"], start: "2026-04-20", due: "2026-05-05", est: 12, prog: 0 }),

  // DOC
  T("DOC-2", "p6", "اختيار محرك التوثيق (Nextra/Docusaurus)", { s: "todo", p: "med", a: ["u4"], start: "2026-04-15", due: "2026-04-22", est: 4, prog: 0 }),
  T("DOC-3", "p6", "تصميم الهوية البصرية للبوابة", { s: "todo", p: "low", a: ["u5"], start: "2026-04-20", due: "2026-05-05", est: 16, prog: 0 }),
];

const ACTIVITY = [
  { who: "u2", action: "أغلق مهمة", target: "PAY-13 تكامل بوابة مدى", when: "قبل 12 د", type: "done" },
  { who: "u4", action: "علّق على", target: "CRM-23 Import من Excel", when: "قبل 28 د", type: "comment" },
  { who: "u6", action: "حدّث حالة", target: "INF-5 إلى محظورة", when: "قبل ساعة", type: "blocked" },
  { who: "u1", action: "أنشأت مهمة", target: "PAY-20 إصلاح تسريب الذاكرة", when: "قبل ساعتين", type: "created" },
  { who: "u5", action: "رفعت مرفقاً على", target: "MOB-18 شاشة التسجيل", when: "قبل 3 س", type: "attachment" },
  { who: "u8", action: "أسندت مهمة إلى عمر", target: "PAY-12", when: "قبل 5 س", type: "assign" },
  { who: "u9", action: "أغلقت مهمة", target: "PAY-10 ترحيل Postgres", when: "أمس", type: "done" },
  { who: "u7", action: "أضافت مراجعة على", target: "DSH-10", when: "أمس", type: "review" },
];

const COMMENTS_BY_TASK = {
  "PAY-12": [
    { u: "u2", when: "قبل 3 س", text: "بدأت بإعادة هيكلة الخدمة. أحتاج مراجعة من @ليلى الحربي على تصميم الـ middleware." },
    { u: "u3", when: "قبل ساعتين", text: "شفت الـ PR. أقترح فصل منطق التوقيع في module مستقل. التعليقات على GitHub." },
    { u: "u2", when: "قبل 45 د", text: "تمام، سأطبّق التعديلات وأرفع نسخة جديدة قبل نهاية اليوم." },
  ],
};

// Localization
const T_AR = {
  dashboard: "لوحة المعلومات",
  projects: "المشاريع",
  myTasks: "مهامي",
  workload: "حمل العمل",
  teams: "الفرق",
  analytics: "التقارير",
  inbox: "الصندوق الوارد",
  settings: "الإعدادات",
  search: "بحث سريع…",
  new: "جديد",
  newTask: "مهمة جديدة",
  newProject: "مشروع جديد",
  filter: "تصفية",
  sort: "ترتيب",
  group: "تجميع",
  overview: "نظرة عامة",
  activity: "النشاط",
  files: "الملفات",
  timeline: "الجدول الزمني",
  board: "لوحة Kanban",
  list: "قائمة",
  gantt: "Gantt",
  calendar: "التقويم",
  status: { todo: "للإنجاز", progress: "قيد التنفيذ", review: "قيد المراجعة", blocked: "محظورة", done: "منتهية" },
  priority: { low: "منخفضة", med: "متوسطة", high: "عالية", crit: "حرجة" },
  today: "اليوم",
  late: "متأخرة",
  due: "الاستحقاق",
  assignee: "المسند إليه",
  progress: "الإنجاز",
  estimate: "تقدير",
  spent: "المنقضي",
  client: "العميل",
  pm: "مدير المشروع",
  budget: "الميزانية",
  description: "الوصف",
  comments: "التعليقات",
  attachments: "المرفقات",
  dependencies: "الاعتماديات",
  subtasks: "المهام الفرعية",
  noResults: "لا توجد نتائج",
  addComment: "أضف تعليقاً… (@ للإشارة)",
  projectsCount: "مشاريع",
  tasksOpen: "مهام مفتوحة",
  overdue: "متأخرة",
  velocity: "Velocity / أسبوع",
  openTasks: "المهام المفتوحة",
  completion: "نسبة الإنجاز",
  topLate: "أعلى المهام تأخراً",
  overloaded: "الأعضاء الأكثر ضغطاً",
  velocityTrend: "Velocity الفريق — آخر 8 أسابيع",
  recentActivity: "النشاط الأخير",
  upcoming: "المستحقات القريبة",
  burn: "Burn-down",
  h: "س",
  d: "يوم",
  week: "أسبوع",
  month: "شهر",
  days: ["أحد", "اثنين", "ثلاثاء", "أربعاء", "خميس", "جمعة", "سبت"],
  months: ["يناير", "فبراير", "مارس", "أبريل", "مايو", "يونيو", "يوليو", "أغسطس", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر"],
};
const T_EN = {
  dashboard: "Dashboard",
  projects: "Projects",
  myTasks: "My Tasks",
  workload: "Workload",
  teams: "Teams",
  analytics: "Analytics",
  inbox: "Inbox",
  settings: "Settings",
  search: "Quick search…",
  new: "New",
  newTask: "New Task",
  newProject: "New Project",
  filter: "Filter",
  sort: "Sort",
  group: "Group",
  overview: "Overview",
  activity: "Activity",
  files: "Files",
  timeline: "Timeline",
  board: "Board",
  list: "List",
  gantt: "Gantt",
  calendar: "Calendar",
  status: { todo: "To Do", progress: "In Progress", review: "In Review", blocked: "Blocked", done: "Done" },
  priority: { low: "Low", med: "Medium", high: "High", crit: "Critical" },
  today: "Today",
  late: "Late",
  due: "Due",
  assignee: "Assignee",
  progress: "Progress",
  estimate: "Estimate",
  spent: "Spent",
  client: "Client",
  pm: "PM",
  budget: "Budget",
  description: "Description",
  comments: "Comments",
  attachments: "Attachments",
  dependencies: "Dependencies",
  subtasks: "Subtasks",
  noResults: "No results",
  addComment: "Add a comment… (@ to mention)",
  projectsCount: "Projects",
  tasksOpen: "Open tasks",
  overdue: "Overdue",
  velocity: "Velocity / wk",
  openTasks: "Open tasks",
  completion: "Completion",
  topLate: "Most overdue",
  overloaded: "Overloaded members",
  velocityTrend: "Team velocity — last 8 weeks",
  recentActivity: "Recent activity",
  upcoming: "Upcoming",
  burn: "Burn-down",
  h: "h",
  d: "d",
  week: "Week",
  month: "Month",
  days: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
};

const TODAY = new Date("2026-04-16");

Object.assign(window, { TEAM, PROJECTS, TASKS, ACTIVITY, COMMENTS_BY_TASK, T_AR, T_EN, TODAY });
